### ISSUE TITLE
Removed from service request - PNGs

### ISSUE THREAD

**Issue by l4red0** [justcoded/just-image-optimizer#9]
Google PageSpeed Insights API seems to have problem with PNG format. In every case it returns "Removed from service request" in log. Wasn't able to find any documentation on that for the google's API, but maybe there should be option to exclude pngs from being added to processing que. Maybe Insights API isn't able to process pngs at all.

Anyhow very nice work with plugin!

**Comment by aprokopenko** [comment]
Wow, first feedback! :)

Thank you for writing to us.

Actually this is not a response from Google API. Google API for optimizing images has a lot of problems inside. Sometimes it return image 25x25 instead of optimized on. For some images it doesn't return anything (maybe think it's already good). For images, which are missing in the response we print such log status. 
Normally it optimizes both JPEG and PNG.
